// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `ticket.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var ticket = __M.module("ticket");

    ticket.Order = Slice.defineStruct(
        function(orderId, phone, orderNum, orderDate, ticketType, amount, orderStatus)
        {
            this.orderId = orderId !== undefined ? orderId : 0;
            this.phone = phone !== undefined ? phone : "";
            this.orderNum = orderNum !== undefined ? orderNum : "";
            this.orderDate = orderDate !== undefined ? orderDate : 0;
            this.ticketType = ticketType !== undefined ? ticketType : 0;
            this.amount = amount !== undefined ? amount : 0.0;
            this.orderStatus = orderStatus !== undefined ? orderStatus : 0;
        },
        false,
        function(__os)
        {
            __os.writeLong(this.orderId);
            __os.writeString(this.phone);
            __os.writeString(this.orderNum);
            __os.writeInt(this.orderDate);
            __os.writeInt(this.ticketType);
            __os.writeDouble(this.amount);
            __os.writeInt(this.orderStatus);
        },
        function(__is)
        {
            this.orderId = __is.readLong();
            this.phone = __is.readString();
            this.orderNum = __is.readString();
            this.orderDate = __is.readInt();
            this.ticketType = __is.readInt();
            this.amount = __is.readDouble();
            this.orderStatus = __is.readInt();
        },
        30, 
        false);
    Slice.defineSequence(ticket, "OrderSeqHelper", "ticket.Order", false);

    ticket.TicketService = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::ticket::TicketService"
        ],
        -1, undefined, undefined, false);

    ticket.TicketServicePrx = Slice.defineProxy(Ice.ObjectPrx, ticket.TicketService.ice_staticId, undefined);

    Slice.defineOperations(ticket.TicketService, ticket.TicketServicePrx,
    {
        "createOrder": [, , , , , [1], [[ticket.Order]], , , , ],
        "queryMyOrders": [, , , , , ["ticket.OrderSeqHelper"], [[7]], , , , ],
        "cancleOrder": [, , , , , [1], [[4]], , , , ]
    });
    exports.ticket = ticket;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
